package org.gxu.design.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.io.Serializable;
import lombok.Data;
import lombok.ToString;

/**
 * 用户实体类
 * @TableName user
 */
@Data
@ToString
@TableName(value ="user")
public class User implements Serializable {
    /**
     * 用户ID
     */
    @TableId
    public int id;

    /**
     * 用户账号
     */
    private String account;

    /**
     * 用户密码
     */
    private String password;

    /**
     * 用户姓名
     */
    private String name;

    /**
     * 用户昵称
     */
    private String nickName;

    /**
     * 用户职位
     */
    private Position position;

    /**
     * 用户部门
     */
    private Department department;

    /**
     * 用户性别
     */
    private String sex;

    /**
     * 用户电话
     */
    private String phone;

    /**
     * 用户邮箱
     */
    private String mailbox;


    // Getters and Setters can be omitted as they are generated by @Data
}
